# Server settings
server:
    tomcat:
        basedir: /var/tmp/website-blog-admin
# SPRING PROFILES
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://106.12.72.177:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: zxlwan19960722
    # 指定默认MimeMessage的编码，默认为: UTF-8
    mail:
        default-encoding: UTF-8
        # 指定SMTP server使用的协议，默认为: smtp
        protocol: smtp
        # 指定SMTP server host.
        host: stmp.qq.com
        port: 465
        # 指定SMTP server的用户名.
        username: 982907295@qq.com
        # 指定SMTP server登陆密码:
        password: zxljgwb19960722
        # 指定是否在启动时测试邮件服务器连接，默认为false
        test-connection: false
        properties:
            mail.smtp.auth: true
            # 腾讯企业邮箱 下两个配置必须！！！
            mail.smtp.ssl.enable: true
            mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
            mail.smtp.socketFactory.port: 465
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.connectiontimeout: 50000
            mail.smtp.timeout: 30000
            mail.smtp.writetimeout: 50000

    # Redis数据库索引（默认为0）
    redis:
        database: 1
        # Redis服务器地址
        host: 106.12.72.177
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: zxlwan19960722
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 5000ms
        # 默认的数据过期时间，主要用于shiro权限管理
        expire: 2592000
# logging settings
logging:
  path: /var/tmp/website-blog-admin
####################################自定义配置##########################################
app:
    # 是否启用kaptcha验证码
    enableKaptcha: false
    # shiro配置项
    shiro:
        loginUrl: "/passport/login/"
        successUrl: "/"
        unauthorizedUrl: "/error/403"
    # 创建网站的时间，用于计算已建站的天数，默认为2018-01-01
    buildWebsiteDate: 2019-01-01 00:00:00
####################################自定义配置##########################################
