# Server settings
server:
    tomcat:
        basedir: /var/tmp/website-blog-web
# SPRING PROFILES
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
    # 指定默认MimeMessage的编码，默认为: UTF-8
    mail:
        default-encoding: UTF-8
        # 指定SMTP server使用的协议，默认为: smtp
        protocol: smtp
        # 指定SMTP server host.
        host: stmp.qq.com
        port: 465
        # 指定SMTP server的用户名.
        username: 982907295@qq.com
        # 指定SMTP server登陆密码:
        password: zxljgwb19960722
        # 指定是否在启动时测试邮件服务器连接，默认为false
        test-connection: false
        properties:
            mail.smtp.auth: true
            # 腾讯企业邮箱 下两个配置必须！！！
            mail.smtp.ssl.enable: true
            mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
            mail.smtp.socketFactory.port: 465
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.connectiontimeout: 50000
            mail.smtp.timeout: 30000
            mail.smtp.writetimeout: 50000
# logging settings
logging:
  path: /var/tmp/website-blog-web
# braum过滤器，用于过滤恶意请求
braum:
    limit:
        access:
            type: redis
            threshold: 15
            interval: 5000
####################################自定义配置##########################################
app:
    # 是否启用kaptcha验证码
    enableKaptcha: false
    # 创建网站的时间，用于计算已建站的天数，默认为2018-01-01
    buildWebsiteDate: 2019-01-01 00:00:00
####################################自定义配置##########################################
